/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Servidor trabajando en la suma. \n");
	printf("Datos: %d, %d\n", argp->a, argp->b);
	result = argp->a + argp->b;
	printf("El resultado es: %d\n", result);
	return &result;
}

int *
resta_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Servidor trabajando en la resta. \n");
	printf("Datos: %d, %d\n", argp->a, argp->b);
	result = argp->a - argp->b;
	printf("El resultado es: %d\n", result);
	return &result;
}

int *
multiplicacion_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Servidor trabajando en la multiplicacion. \n");
	printf("Datos: %d, %d\n", argp->a, argp->b);
	result = argp->a * argp->b;
	printf("El resultado es: %d\n", result);
	return &result;
}

int *
division_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("Servidor trabajando en la division. \n");
	printf("Datos: %d, %d\n", argp->a, argp->b);
	result = argp->a / argp->b;
	printf("El resultado es: %d\n", result);
	return &result;
}