/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <string.h>	

void
calculadora_prog_1(char *host, int a, int select, int b)
{
	CLIENT *clnt;
	int  *result_1;
	dupla_int  datos_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	datos_1_arg.a = a;
	datos_1_arg.b = b;

if (select == 1){
	result_1 = suma_1(&datos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Resultado de la suma: %d\n", *result_1);
}

else if (select == 2){
	result_1 = resta_1(&datos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("Resultado de la resta: %d\n", *result_1);
}

else if (select == 3){
	result_1 = multiplicacion_1(&datos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
		printf("Resultado de la multiplicacion: %d\n", *result_1);
}

else if (select == 4){
	result_1 = division_1(&datos_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
		printf("Resultado de la division: %d\n", *result_1);
}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host,*operacion;
	int a, b, select;

	if (argc != 5) {
		printf ("usage: %s server_host operation a b\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	operacion = argv[3];

	if ((a = atoi(argv[2])) == 0 && *argv[2] != '0') {
		fprintf(stderr, "invalid value: %s\n", argv[2]);
		exit(1);
	}
	if ((b = atoi(argv[4])) == 0 && *argv[4] != '0') {
		fprintf(stderr, "invalid value: %s\n", argv[3]);
		exit(1);
	}

	if (strcmp(operacion, "+") == 0)
		select = 1;
	else if (strcmp(operacion, "-") == 0)
		select = 2;
	else if(strcmp(operacion, "x") == 0)
		select = 3;
	else if(strcmp(operacion, "/") == 0)
		select = 4;
	else
		printf("Esa operacion no esta disponible. :c\n");

	calculadora_prog_1 (host, a, select,b);
	exit (0);
}
